name: athkar_app
description: تطبيق الأذكار - رفيقك اليومي للأذكار والتسبيح مع عداد تفاعلي أنيق وحاسبة استغفار

publish_to: 'none'

version: 1.0.0+1

# App Information for Release
author: Zoheir
homepage: https://github.com/zoheir/athkar-app

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  # fonts:
    # - family: Amiri
    #   fonts:
    #     - asset: assets/fonts/Amiri-Regular.ttf
    #     - asset: assets/fonts/Amiri-Bold.ttf
    #       weight: 700

# App Icon Configuration
flutter_launcher_icons:
  android: "ic_launcher"
  image_path: "assets/images/app_icon.png"
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#2E8B57"
    theme_color: "#2E8B57"